Added submit button, answer checking, and different screens
JoshAdamPowell/QuizApp pull request #15
Opened 2021-09-13 16:33 UTC by TheConfuZzledDude

Quiz is now pretty much all functional with this, but all quizzes are assumed to be AND-style multiple answer questions

2021-09-13 16:55 UTC, JoshAdamPowell reviewed
Lookgs good! Will finish off the review tomorrow :)

2021-09-13 16:55 UTC, JoshAdamPowell commented on src/component/ChildSwitcherContainer.tsx
> +}: ChildSwitcherContainerProps): React.ReactElement => (
think this and line 5 can be `React.ReactChildren`

2021-09-13 16:55 UTC, JoshAdamPowell commented on src/view/QuizView.tsx
> +  setSelectedAnswers?: React.Dispatch<React.SetStateAction<AnswerSelections>>;
do you think this is clearer than `setSelectedAnswers?: (selections: AnswerSelections) => void;`

I think you can make arguments for either but the arrow function notation is a little clearer. Happy to be pushed back though

2021-09-13 16:55 UTC, JoshAdamPowell commented on src/view/QuizView.tsx
> +            quizName={"Quiz is over, go home losers"}
lol

2021-09-13 16:55 UTC, JoshAdamPowell commented on src/view/QuizView.tsx
> +const Container = styled.div`
can you put this into a styled.ts? this file is getting a little big

2021-09-13 16:55 UTC, JoshAdamPowell commented on src/component/ChildSwitcherContainer.tsx
> +}: ChildSwitcherContainerProps): React.ReactElement => (
(might need to slightly tweak where its used)

2021-09-14 09:24 UTC, TheConfuZzledDude commented on src/component/ChildSwitcherContainer.tsx
> +}: ChildSwitcherContainerProps): React.ReactElement => (
I've changed line 5 and that works (and is probably better), and I've changed line 11 to be React.ReactChild which I think is more accurate to what the component is doing

2021-09-14 09:25 UTC, TheConfuZzledDude commented on src/view/QuizView.tsx
> +  setSelectedAnswers?: React.Dispatch<React.SetStateAction<AnswerSelections>>;
Personally I think just stating it's a normal function hides a lot of the React boilerplate, and it's nice to know later on that this function is actually setting React state later down. I think the React.Dispatch can be safely removed though, so I've done that for now.

2021-09-14 09:36 UTC, TheConfuZzledDude commented on src/component/ChildSwitcherContainer.tsx
> +}: ChildSwitcherContainerProps): React.ReactElement => (
Actually nevermind, React.ReactChild doesn't work at all. I think it should still React.ReactElement on line 11

2021-09-14 09:38 UTC, TheConfuZzledDude commented on src/view/QuizView.tsx
> +  setSelectedAnswers?: React.Dispatch<React.SetStateAction<AnswerSelections>>;
Actually looking at the type signatures more carefully, I think the Dispatch is necessary. `setSelectedAnswers?: (selections: AnswerSelections) => void;` isn't a complete signature, it would actually be `setSelectedAnswers?: (selections: AnswerSelections | ((prevState: AnswerSelections) => Answer Selections) => void;` because you can provide it an update function instead of just the new state (and we probably should in a few places

2021-09-14 10:01 UTC, TraySoft commented on src/component/AnswerButton/styled.ts
> +  revealed?: boolean;
I think all optional except for correct which should always be known

2021-09-14 10:07 UTC, TraySoft requested changes
Looks mostly good to me, few minor comments to address

2021-09-14 10:07 UTC, TraySoft commented on src/component/QuestionResult/QuestionResult.tsx
> +      )}
love it

2021-09-14 10:07 UTC, TraySoft commented on src/view/QuizView.tsx
> +      setQuestionStates(questionStates.fill(QuestionState.UNANSWERED));
Won't this line erase our information for reporting scores on the final screen?

2021-09-14 10:36 UTC, FuZzledd commented on src/view/QuizView.tsx
> +      setQuestionStates(questionStates.fill(QuestionState.UNANSWERED));
Yes it would, it won't now :)

2021-09-14 10:47 UTC, TraySoft approved these changes
LGTM

2021-09-14 10:48 UTC, merged